#!/usr/bin/env python
"""
Test runner script for the API project.

This script provides a convenient way to run tests with different configurations
and generate detailed reports.
"""

import os
import sys
import subprocess
import django
from django.test.utils import get_runner
from django.conf import settings

def run_tests_with_coverage():
    """Run tests with coverage reporting."""
    try:
        import coverage
    except ImportError:
        print("Coverage not installed. Install with: pip install coverage")
        return
    
    # Start coverage
    cov = coverage.Coverage()
    cov.start()
    
    # Run tests
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'advanced_api_project.settings')
    django.setup()
    TestRunner = get_runner(settings)
    test_runner = TestRunner(verbosity=2)
    failures = test_runner.run_tests(['api'])
    
    # Stop coverage and generate report
    cov.stop()
    cov.save()
    
    print("\n" + "="*70)
    print("COVERAGE REPORT")
    print("="*70)
    cov.report()
    
    # Generate HTML report
    cov.html_report(directory='htmlcov')
    print("\nHTML report generated in htmlcov/ directory")
    
    return failures

if __name__ == '__main__':
    if '--coverage' in sys.argv:
        failures = run_tests_with_coverage()
    else:
        # Run normal tests
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'advanced_api_project.settings')
        django.setup()
        from django.test.utils import get_runner
        from django.conf import settings
        
        TestRunner = get_runner(settings)
        test_runner = TestRunner(verbosity=2)
        failures = test_runner.run_tests(['api'])
    
    sys.exit(bool(failures))
